/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author o.o
 */
public class InicioSesion extends javax.swing.JFrame {

    private ImageIcon imagen;
    private ImageIcon icono;

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        
        bgInicio.setSize(800, 600);
        bgInicio.setLocation(0, 0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonregistrarse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        eslogan = new javax.swing.JLabel();
        degradado = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        inicio1 = new javax.swing.JLabel();
        botoninicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        bgInicio.setBackground(new java.awt.Color(255, 255, 255));
        bgInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Aun no tienes una cuenta?");
        bgInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 200, 50));

        botonregistrarse.setBackground(new java.awt.Color(204, 51, 255));
        botonregistrarse.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonregistrarse.setForeground(new java.awt.Color(255, 255, 255));
        botonregistrarse.setText("Registrate");
        botonregistrarse.setBorder(null);
        botonregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregistrarseActionPerformed(evt);
            }
        });
        bgInicio.add(botonregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 140, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SaludXpert");
        bgInicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        eslogan.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        eslogan.setForeground(new java.awt.Color(255, 255, 255));
        eslogan.setText("Citas rápidas, salud eficiente. ");
        bgInicio.add(eslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        degradado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saludxpert/imagenes/fondo.png"))); // NOI18N
        bgInicio.add(degradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 600));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        usuario.setMargin(new java.awt.Insets(0, 10, 0, 0));
        usuario.setOpaque(false);
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        bgInicio.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 390, 60));

        inicio1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        inicio1.setForeground(new java.awt.Color(0, 102, 255));
        inicio1.setText("Iniciar Sesion");
        bgInicio.add(inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 300, 60));

        botoninicio.setBackground(new java.awt.Color(51, 102, 255));
        botoninicio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botoninicio.setForeground(new java.awt.Color(255, 255, 255));
        botoninicio.setText("Iniciar Sesion");
        botoninicio.setBorder(null);
        bgInicio.add(botoninicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 250, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Usuario");
        bgInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 130, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Contraseña");
        bgInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 130, 20));

        contraseña.setBackground(new java.awt.Color(255, 255, 255));
        contraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(0, 0, 0));
        contraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        contraseña.setMargin(new java.awt.Insets(0, 5, 0, 0));
        contraseña.setOpaque(false);
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        bgInicio.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 390, 60));

        jCheckBox1.setBackground(new java.awt.Color(51, 153, 255));
        jCheckBox1.setText("Recuerdame");
        jCheckBox1.setOpaque(false);
        bgInicio.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel4.setText("¿Olvidaste tu contraseña?");
        bgInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregistrarseActionPerformed
      
        Registrarse registrase = new Registrarse();
        registrase.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonregistrarseActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
      private void ajustarImg(JLabel label, String ruta){
    this.imagen = new ImageIcon(ruta);
    this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(label.getWidth(), label.getHeight(), 
            Image.SCALE_DEFAULT));
    
    label.setIcon(this.icono);
    this.repaint();
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgInicio;
    private javax.swing.JButton botoninicio;
    private javax.swing.JButton botonregistrarse;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel degradado;
    private javax.swing.JLabel eslogan;
    private javax.swing.JLabel inicio1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
