/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author o.o
 */
public class PantallaDoctores extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDoctores
     */
    public PantallaDoctores() {
         this.setExtendedState(PantallaPaciente.MAXIMIZED_BOTH);
        initComponents();
         this.setExtendedState(PantallaPaciente.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Administradortexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Admiicono = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblDoctores = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblEspecialidades = new javax.swing.JLabel();
        lblRecepcionista = new javax.swing.JLabel();
        lblInformacion1 = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        Pantallas = new javax.swing.JTabbedPane();
        PBienvenida = new javax.swing.JTabbedPane();
        pRecepcionista = new javax.swing.JTabbedPane();
        pEspecialidades = new javax.swing.JTabbedPane();
        pDoctores = new javax.swing.JTabbedPane();
        pSistema = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1000, 1148));

        Menu.setBackground(new java.awt.Color(83, 121, 235));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Administradortexto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Administradortexto.setForeground(new java.awt.Color(255, 255, 255));
        Administradortexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Administradortexto.setText("Doctores");
        Menu.add(Administradortexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 232, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 172, 232, 10));

        Admiicono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Admiicono.setIcon(new FlatSVGIcon("Vista/imagenes/Person.svg"));
        Menu.add(Admiicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 232, 88));

        lblBienvenida.setBackground(new java.awt.Color(83, 121, 235));
        lblBienvenida.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setIcon(new FlatSVGIcon("Vista/imagenes/home.svg"));
        lblBienvenida.setText("Panel Principal");
        lblBienvenida.setToolTipText("");
        lblBienvenida.setOpaque(true);
        lblBienvenida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBienvenidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBienvenidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBienvenidaMouseExited(evt);
            }
        });
        Menu.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 70));

        lblDoctores.setBackground(new java.awt.Color(83, 121, 235));
        lblDoctores.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblDoctores.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctores.setIcon(new FlatSVGIcon("Vista/imagenes/coracon+.svg"));
        lblDoctores.setText("Doctores");
        lblDoctores.setMaximumSize(new java.awt.Dimension(91, 18));
        lblDoctores.setMinimumSize(new java.awt.Dimension(91, 18));
        lblDoctores.setOpaque(true);
        lblDoctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoctoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoctoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoctoresMouseExited(evt);
            }
        });
        Menu.add(lblDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 200, 70));

        lblSalir.setBackground(new java.awt.Color(83, 121, 235));
        lblSalir.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new FlatSVGIcon("Vista/imagenes/saliraplicacion.svg"));
        lblSalir.setText("Salir");
        lblSalir.setOpaque(true);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        Menu.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 200, 60));

        lblEspecialidades.setBackground(new java.awt.Color(83, 121, 235));
        lblEspecialidades.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblEspecialidades.setForeground(new java.awt.Color(255, 255, 255));
        lblEspecialidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspecialidades.setIcon(new FlatSVGIcon("Vista/imagenes/herramienta.svg"));
        lblEspecialidades.setText("Especialidades");
        lblEspecialidades.setOpaque(true);
        lblEspecialidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEspecialidadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEspecialidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEspecialidadesMouseExited(evt);
            }
        });
        Menu.add(lblEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 70));

        lblRecepcionista.setBackground(new java.awt.Color(83, 121, 235));
        lblRecepcionista.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        lblRecepcionista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecepcionista.setIcon(new FlatSVGIcon("Vista/imagenes/compu.svg"));
        lblRecepcionista.setText("Recepcionista");
        lblRecepcionista.setOpaque(true);
        lblRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecepcionistaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRecepcionistaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRecepcionistaMouseExited(evt);
            }
        });
        Menu.add(lblRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 70));

        lblInformacion1.setBackground(new java.awt.Color(83, 121, 235));
        lblInformacion1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblInformacion1.setForeground(new java.awt.Color(255, 255, 255));
        lblInformacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacion1.setIcon(new FlatSVGIcon("Vista/imagenes/informacion.svg"));
        lblInformacion1.setText("Sistema");
        lblInformacion1.setOpaque(true);
        lblInformacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInformacion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInformacion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInformacion1MouseExited(evt);
            }
        });
        Menu.add(lblInformacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 200, 60));

        lblFechaActual.setBackground(new java.awt.Color(71, 112, 233));
        lblFechaActual.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        lblFechaActual.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaActual.setText("Fecha:");
        lblFechaActual.setOpaque(true);

        PBienvenida.setBackground(new java.awt.Color(255, 204, 153));
        PBienvenida.setOpaque(true);
        Pantallas.addTab("tab1", PBienvenida);

        pRecepcionista.setBackground(new java.awt.Color(0, 255, 0));
        pRecepcionista.setOpaque(true);
        Pantallas.addTab("tab2", pRecepcionista);

        pEspecialidades.setBackground(new java.awt.Color(51, 102, 255));
        pEspecialidades.setOpaque(true);
        Pantallas.addTab("tab3", pEspecialidades);

        pDoctores.setBackground(new java.awt.Color(51, 204, 255));
        pDoctores.setOpaque(true);
        Pantallas.addTab("tab4", pDoctores);

        pSistema.setBackground(new java.awt.Color(0, 153, 153));
        pSistema.setOpaque(true);
        Pantallas.addTab("tab5", pSistema);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(Pantallas))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1100, 1100, 1100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBienvenidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBienvenidaMouseClicked
        Pantallas.setSelectedIndex(0);
    }//GEN-LAST:event_lblBienvenidaMouseClicked

    private void lblBienvenidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBienvenidaMouseEntered
        lblBienvenida.setBackground(new Color(42,72,161));
    }//GEN-LAST:event_lblBienvenidaMouseEntered

    private void lblBienvenidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBienvenidaMouseExited
        lblBienvenida.setBackground(new Color(83,121,235));
    }//GEN-LAST:event_lblBienvenidaMouseExited

    private void lblDoctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctoresMouseClicked
        Pantallas.setSelectedIndex(3);
    }//GEN-LAST:event_lblDoctoresMouseClicked

    private void lblDoctoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctoresMouseEntered
        lblDoctores.setBackground(new Color(42,72,161));
    }//GEN-LAST:event_lblDoctoresMouseEntered

    private void lblDoctoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctoresMouseExited
        lblDoctores.setBackground(new Color(83,121,235));
    }//GEN-LAST:event_lblDoctoresMouseExited

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        lblSalir.setBackground(new Color(42,72,161));
        PantallaInicioSesion inicio = new PantallaInicioSesion();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        lblSalir.setBackground(new Color(42,72,161));
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBackground(new Color(83,121,235));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblEspecialidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspecialidadesMouseClicked
        Pantallas.setSelectedIndex(2);
    }//GEN-LAST:event_lblEspecialidadesMouseClicked

    private void lblEspecialidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspecialidadesMouseEntered
        lblEspecialidades.setBackground(new Color(42,72,161));
    }//GEN-LAST:event_lblEspecialidadesMouseEntered

    private void lblEspecialidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspecialidadesMouseExited
        lblEspecialidades.setBackground(new Color(83,121,235));
    }//GEN-LAST:event_lblEspecialidadesMouseExited

    private void lblRecepcionistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecepcionistaMouseClicked
        Pantallas.setSelectedIndex(1);
    }//GEN-LAST:event_lblRecepcionistaMouseClicked

    private void lblRecepcionistaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecepcionistaMouseEntered
        lblRecepcionista.setBackground(new Color(42,72,161));
    }//GEN-LAST:event_lblRecepcionistaMouseEntered

    private void lblRecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecepcionistaMouseExited
        lblRecepcionista.setBackground(new Color(83,121,235));
    }//GEN-LAST:event_lblRecepcionistaMouseExited

    private void lblInformacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformacion1MouseClicked
        Pantallas.setSelectedIndex(4);
    }//GEN-LAST:event_lblInformacion1MouseClicked

    private void lblInformacion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformacion1MouseEntered
        lblInformacion1.setBackground(new Color(42,72,161));
    }//GEN-LAST:event_lblInformacion1MouseEntered

    private void lblInformacion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformacion1MouseExited
        lblInformacion1.setBackground(new Color(83,121,235));
    }//GEN-LAST:event_lblInformacion1MouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//       try {
//            
//          FlatMacLightLaf.setup();
//          UIManager.put("Component.innerFocusWidth", 3);
//         
//        } catch (Exception ex) {
//            System.err.println("No se pudo cargar el tema FlatLaf MacOS Light.");
//            ex.printStackTrace();
//        }
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaDoctores().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admiicono;
    private javax.swing.JLabel Administradortexto;
    private javax.swing.JPanel Menu;
    private javax.swing.JTabbedPane PBienvenida;
    private javax.swing.JTabbedPane Pantallas;
    private javax.swing.JPanel bg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblDoctores;
    private javax.swing.JLabel lblEspecialidades;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblInformacion1;
    private javax.swing.JLabel lblRecepcionista;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JTabbedPane pDoctores;
    private javax.swing.JTabbedPane pEspecialidades;
    private javax.swing.JTabbedPane pRecepcionista;
    private javax.swing.JTabbedPane pSistema;
    // End of variables declaration//GEN-END:variables
}
