package Vista;

import Modelo.RegistrarseDB;
import javax.swing.JOptionPane;
import Modelo.Usuarios;
import Modelo.UsuariosDAO;

/**
 *
 * @author o.o
 */
public class PantallaRegistrarse extends javax.swing.JFrame {

    private RegistrarseDB pacienteModelo;

    /**
     * Creates new form PantallaRegistrarse
     */
    public PantallaRegistrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGenero = new javax.swing.ButtonGroup();
        plBackground = new javax.swing.JPanel();
        lblNombrePantalla = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();
        lblMensaje2 = new javax.swing.JLabel();
        lblMensaje3 = new javax.swing.JLabel();
        lblDoctoresImg = new javax.swing.JLabel();
        lblMensaje4 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();
        plFormularioRegistro = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        iconUsuario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        iconEmail = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        iconTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        iconPassword = new javax.swing.JLabel();
        iconEye = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblGenero = new javax.swing.JLabel();
        rbtnFemenino = new javax.swing.JRadioButton();
        rbtnMasculino = new javax.swing.JRadioButton();
        btnCapturarDatos = new javax.swing.JButton();
        btnPaciente = new javax.swing.JButton();

        btngGenero.add(rbtnFemenino);
        btngGenero.add(rbtnMasculino);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plBackground.setBackground(new java.awt.Color(255, 255, 255));
        plBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombrePantalla.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        lblNombrePantalla.setForeground(new java.awt.Color(204, 51, 255));
        lblNombrePantalla.setText("Regístrate");
        plBackground.add(lblNombrePantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, 60));

        lblMensaje1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 35)); // NOI18N
        lblMensaje1.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMensaje1.setText("¡Crea tu cuenta!");
        plBackground.add(lblMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, 50));

        lblMensaje2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        lblMensaje2.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje2.setText("y organiza citas eficientes");
        plBackground.add(lblMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 270, 50));

        lblMensaje3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        lblMensaje3.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje3.setText("desde el primer momento.");
        plBackground.add(lblMensaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 290, 40));

        lblDoctoresImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/doctores.png"))); // NOI18N
        plBackground.add(lblDoctoresImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 310, 220));

        lblMensaje4.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        lblMensaje4.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje4.setText("¿Ya tienes una cuenta? ");
        plBackground.add(lblMensaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(51, 102, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText(" Iniciar sesión");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        plBackground.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 180, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/fondo.png"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(390, 670));
        Fondo.setMinimumSize(new java.awt.Dimension(390, 670));
        Fondo.setPreferredSize(new java.awt.Dimension(390, 670));
        plBackground.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 390, 670));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plFormularioRegistro.setBackground(new java.awt.Color(255, 255, 255));
        plFormularioRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(153, 153, 153));
        lblNombre.setText("Nombre");
        plFormularioRegistro.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 20));

        iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/usuario.png"))); // NOI18N
        plFormularioRegistro.add(iconUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 30, 50));

        txtNombre.setBackground(new java.awt.Color(235, 235, 234));
        txtNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 234), 4));
        txtNombre.setMargin(new java.awt.Insets(0, 25, 0, 0));
        txtNombre.setMaximumSize(new java.awt.Dimension(15, 24));
        plFormularioRegistro.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 40));

        lblApellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(153, 153, 153));
        lblApellido.setText("Apellido ");
        plFormularioRegistro.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 130, 20));

        txtApellido.setBackground(new java.awt.Color(235, 235, 234));
        txtApellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 234), 4));
        txtApellido.setMargin(new java.awt.Insets(0, 15, 0, 0));
        txtApellido.setMaximumSize(new java.awt.Dimension(15, 24));
        plFormularioRegistro.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 230, 40));

        lblCorreo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(153, 153, 153));
        lblCorreo.setText("Correo Electrónico");
        plFormularioRegistro.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, 20));

        iconEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/email.png"))); // NOI18N
        plFormularioRegistro.add(iconEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, 20));

        txtCorreo.setBackground(new java.awt.Color(235, 235, 234));
        txtCorreo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 234), 4));
        txtCorreo.setMargin(new java.awt.Insets(0, 25, 0, 0));
        txtCorreo.setMaximumSize(new java.awt.Dimension(15, 24));
        plFormularioRegistro.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 440, 40));

        lblTelefono.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(153, 153, 153));
        lblTelefono.setText("Teléfono");
        plFormularioRegistro.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 20));

        iconTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/telefono.png"))); // NOI18N
        plFormularioRegistro.add(iconTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 156, 30, -1));

        txtTelefono.setBackground(new java.awt.Color(235, 235, 234));
        txtTelefono.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 234), 4));
        txtTelefono.setMargin(new java.awt.Insets(0, 25, 0, 0));
        txtTelefono.setMaximumSize(new java.awt.Dimension(15, 24));
        plFormularioRegistro.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 40));

        lblCedula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(153, 153, 153));
        lblCedula.setText("Número de Cédula");
        plFormularioRegistro.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 170, 20));

        txtCedula.setBackground(new java.awt.Color(235, 235, 234));
        txtCedula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(102, 102, 102));
        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 235, 234), 4));
        txtCedula.setMargin(new java.awt.Insets(0, 15, 0, 0));
        txtCedula.setMaximumSize(new java.awt.Dimension(15, 24));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        plFormularioRegistro.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 180, 40));

        lblContraseña.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(153, 153, 153));
        lblContraseña.setText("Contraseña");
        plFormularioRegistro.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 30));

        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/password.png"))); // NOI18N
        plFormularioRegistro.add(iconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 30, 30));

        iconEye.setForeground(java.awt.Color.white);
        iconEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/eye_24.png"))); // NOI18N
        iconEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconEyeMouseClicked(evt);
            }
        });
        plFormularioRegistro.add(iconEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 270, 30, 40));
        plFormularioRegistro.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 40));

        lblGenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblGenero.setText("Género");
        plFormularioRegistro.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 30));

        rbtnFemenino.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rbtnFemenino.setForeground(new java.awt.Color(102, 102, 102));
        rbtnFemenino.setText("Femenino");
        rbtnFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemeninoActionPerformed(evt);
            }
        });
        plFormularioRegistro.add(rbtnFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, -1));

        rbtnMasculino.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rbtnMasculino.setForeground(new java.awt.Color(102, 102, 102));
        rbtnMasculino.setText("Masculino");
        plFormularioRegistro.add(rbtnMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 90, -1));

        btnCapturarDatos.setBackground(new java.awt.Color(204, 51, 255));
        btnCapturarDatos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCapturarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCapturarDatos.setText("Capturar Datos");
        btnCapturarDatos.setBorder(null);
        btnCapturarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarDatosActionPerformed(evt);
            }
        });
        plFormularioRegistro.add(btnCapturarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 250, 60));

        Contenedor.add(plFormularioRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 530));

        plBackground.add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 540, 570));

        btnPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnPaciente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnPaciente.setForeground(new java.awt.Color(102, 102, 102));
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/recepcion1.png"))); // NOI18N
        btnPaciente.setText("Paciente");
        btnPaciente.setFocusPainted(false);
        btnPaciente.setFocusable(false);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        plBackground.add(btnPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 170, 50));

        getContentPane().add(plBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 930, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        PantallaInicioSesion inicio = new PantallaInicioSesion();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
//        TablaOpciones.setSelectedIndex(1);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnCapturarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarDatosActionPerformed

        Usuarios u = new Usuarios();
        UsuariosDAO r = new UsuariosDAO();

        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String correo = txtCorreo.getText();
        String numero_telefono = txtTelefono.getText();
        String cedula = txtCedula.getText();
        String contraseña = txtPassword.getText();
        String genero = rbtnFemenino.isSelected() ? "Femenino" : "Masculino";

        u.setNombre(nombre);
        u.setApellido(apellido);
        u.setCedula(cedula);
        u.setCorreo(correo);
        u.setGenero(genero);
        u.setNumeroTelefono(numero_telefono);
        u.setContraseña(contraseña);

        r.agregar(u);

        JOptionPane.showMessageDialog(null,
                "¡Datos de " + u.getNombre() + " capturados exitosamente!",
                "Confirmación",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCapturarDatosActionPerformed

    private void iconEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEyeMouseClicked
        // TODO add your handling code here:
        // Cambiar entre mostrar y ocultar la contraseña
        if (txtPassword.getEchoChar() == '\u0000') {
            // Ocultar la contraseña
            txtPassword.setEchoChar('*'); // Usamos '*' como carácter para ocultar
        } else {
            // Mostrar la contraseña
            txtPassword.setEchoChar('\u0000'); // '\u0000' muestra el texto sin máscara
        }
    }//GEN-LAST:event_iconEyeMouseClicked

    private void rbtnFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemeninoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCapturarDatos;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnPaciente;
    private javax.swing.ButtonGroup btngGenero;
    private javax.swing.JLabel iconEmail;
    private javax.swing.JLabel iconEye;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconTelefono;
    private javax.swing.JLabel iconUsuario;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDoctoresImg;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblMensaje2;
    private javax.swing.JLabel lblMensaje3;
    private javax.swing.JLabel lblMensaje4;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombrePantalla;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel plBackground;
    private javax.swing.JPanel plFormularioRegistro;
    private javax.swing.JRadioButton rbtnFemenino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
